[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[dependencies]
dioxus = { version = "0.6.0-alpha.4", features = ["web"] }

# Debug
dioxus-logger = "0.5.1"